
spring:

  devtools:
    restart:
      enabled: true
      exclude: static
      additional-paths: src/main/java
      additional-exclude: src/main/resource/static

  mvc:
    static-path-pattern: /static/**
  #修改默认的静态寻址资源目录
    resources:
      static-locations: classpath:/templates/**,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/**,classpath:/public/
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 6000
      time-between-eviction-runs-millis: 300000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eazymusic?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 818923
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html


mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 80
